# Workloads information
---
globalVariables:
  namespace:        "yuruna"
  containerPrefix:  "yuruna"
  registryName:     "yuruna.azurecr.io"

workloads:
- context: "yuruna"
  deployments:
  - chart: "frontend/website"
    variables:
      ipName:   "localhost"
      ipAddres: "127.0.0.1"
      site:     "localhost"
      certManagerIssuerEmail: "certificates@yuruna.com"
