# Components information - localhost
---
globalVariables:
  containerPrefix:  "yrn42mean"
  registryLocation: "localhost:5000"
  registryName:     "localhost"
  buildCommand: docker build --rm -f ${env:dockerfile} -t "${env:containerPrefix}/${env:project}:latest" "${env:buildPath}"
  tagCommand: docker tag "${env:containerPrefix}/${env:project}:latest" "${env:registryLocation}/${env:containerPrefix}/${env:project}:latest"
  pushCommand: docker push "${env:registryLocation}/${env:containerPrefix}/${env:project}:latest"

components:
- project:   "backend"
  buildPath: "mean-api"
  variables:
- project:   "website"
  buildPath: "mean-web"
  variables:
- project:   "database"
  buildPath: "db"
  variables:
