# Resources information
---
globalVariables:
  namespace: "yuruna"
  clusterDnsPrefix: "yuruna"
  clusterName:      "yuruna"
  clusterRegion:    "westus2"
  clusterVersion:   "1.20.0"
  frontendIpName:   "localhost"
  resourceGroup:    "yuruna"
  resourceTags:     "yuruna"
  nodeCount:        1
  registryName:   "localhost:5000"

resources:
# regions: https://cloud.google.com/about/locations
- name:             "yuruna-gke"
  template:         "gcp-gke-cluster"
  variables:
    clusterRegion:  "us-west2"
    clusterVersion: "1.19"
    nodeType:       "n1-standard-1"
