apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.installName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.selectorLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.selectorLabel }}
    spec:
      containers:
      - name: website
        image: {{ .Values.registryLocation }}/{{ .Values.containerPrefix }}/database:latest
        imagePullPolicy: Always 
        ports:
        - name: port80
          containerPort: 9201
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
          - name: "gravaEndpoint"
            value: {{ .Values.gravaEndpoint }}
      imagePullSecrets:
        - name: registry-credential
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.installName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.selectorLabel }}
spec:
  type: LoadBalancer
  ports:
    - name: port80
      port: {{ .Values.servicePort }}
      targetPort: 9201
  selector:
    app: {{ .Values.selectorLabel }}
