# Resources information - azure
---
globalVariables:
  namespace: "yrn42website-namespace"
  clusterDnsPrefix: "yrn42website-dns"
  frontendIpName:   "yrn42website-ip-name"
  resourceGroup:    "yrn42website-resource-group"
  resourceTags:     "yrn42website-tags"
  nodeCount:        3
# TO-SET: registry name must be globally unique
  registryName:     ""

resources:
# regions: az account list-locations -o table
- name:             "yrn42website-cluster-name-aks"
  template:         "azure-aks-cluster"
  variables:
    clusterRegion:  "westus2"
    clusterVersion: "1.19.3"
    nodeType:       "Standard_D2_v2"
    clusterName:    "yrn42website-cluster-name-aks"
