# Resources information - localhost
---
globalVariables:
  namespace: "yuruna"
  clusterDnsPrefix: "yuruna"
  clusterName:      "yuruna"
  clusterRegion:    "westus2"
  clusterVersion:   "1.20.0"
  frontendIpName:   "localhost"
  resourceGroup:    "yuruna"
  resourceTags:     "yuruna"
  nodeCount:        1
  registryName:     "localhost:5000"

resources:
# Localhost with Docker Desktop
# Nothing needs to be created: just provide cluster name
- name:             "docker-desktop"
  template:         ""
  variables:
# Terraform template will run local registry
- name:             "localhost-registry"
  template:         "localhost-registry"
  variables:
