# Workloads information - localhost
---
globalVariables:
  namespace:         "yuruna"
  containerPrefix:   "yuruna"
  registryLocation:  "localhost:5000"
  registryName:      "localhost"
  frontendIpName:    "localhost"
  frontendIpAddress: "127.0.0.1"
  site:              "localhost"
  dockerUsername:    "dummy"
  dockerPassword:    "dummy"
  certManagerIssuerEmail: "certificates@yuruna.com"
  websiteTlsSecret:  "website-tls-secret"

workloads:
- context: "docker-desktop"
  deployments:
  # Uninstall previous workloads: idempotent
  - kubectl: "delete namespace ${env:namespace} --v=1"
  - kubectl: "delete namespace cert-manager --v=1"
  - kubectl: "delete namespace ingress-basic --v=1"
  - kubectl: "delete -f https://github.com/jetstack/cert-manager/releases/download/v1.1.0/cert-manager.yaml --v=1"
  - kubectl: "delete clusterrole nginx-ingress-ingress-nginx"
  - kubectl: "delete clusterrolebinding nginx-ingress-ingress-nginx"
  - shell: "Start-Sleep -s 9"
  # Install dependencies
  - kubectl: "create namespace ${env:namespace} --v=1"
  - kubectl: "create namespace cert-manager --v=1"
  - kubectl: "create namespace ingress-basic --v=1"
  - kubectl: "label namespace cert-manager certmanager.k8s.io/disable-validation=true --v=1"
  - kubectl: "config set-context --current --namespace=${env:namespace} --v=1"
  - helm: "repo add ingress-nginx https://kubernetes.github.io/ingress-nginx"
  - helm: "repo add jetstack https://charts.jetstack.io"
  - helm: "repo update"
  - shell: "Start-Sleep -s 9"
  - helm: >
      install cert-manager jetstack/cert-manager
      --namespace cert-manager
      --version v1.1.0
      --set installCRDs=true
      --set nodeSelector."beta\.kubernetes\.io/os"=linux
      # --debug
  # For localhost: create certificate
  - shell: "mkcert -install"
  - shell: "mkcert -key-file \"${env:workFolder}/website-tls.key\" -cert-file \"${env:workFolder}/website-tls.crt\" yuruna.com \"*.yuruna.com\" yuruna.test localhost \"*.localhost\" 127.0.0.1 ::1"
  - kubectl: "create secret tls ${env:websiteTlsSecret} --key \"${env:workFolder}/website-tls.key\" --cert \"${env:workFolder}/website-tls.crt\" --namespace=${env:namespace}"
  - shell: "Start-Sleep -s 9"
  - helm: >
      install nginx-ingress ingress-nginx/ingress-nginx
      --namespace ingress-basic
      --set controller.replicaCount=2
      --set controller.nodeSelector."beta\.kubernetes\.io/os"=linux
      --set defaultBackend.nodeSelector."beta\.kubernetes\.io/os"=linux
      --set controller.service.loadBalancerIP="${env:frontendIpAddress}"
      --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-dns-label-name"="${env:frontendIpName}"
      --set controller.admissionWebhooks.enabled=false
      # --debug
  # Wait for dependencies to be ready
  - shell: "Start-Sleep -s 9"
  # Install components
  - kubectl: "create secret docker-registry registry-credential --docker-server=http://${env:registryLocation} --docker-username=${env:dockerUsername} --docker-password=${env:dockerPassword}"
  - chart: "frontend/website"
    variables:
      installName: "yuruna-website"
